name: irsa-docs
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - pip=24.0
  - python=3.10.14
  - numpy=1.24.4
  - scipy=1.8.1
  - pandas=2.2.2
  - pytorch=2.2.0
  - scikit-learn=1.5.1
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - torchdata=0.4.1
  - seaborn=0.13.2
  - matplotlib=3.9.1
  - statsmodels=0.14.2
  - rdkit
  - joblib=1.4.2
  - ipython
  - nbsphinx
  - sphinx >= 3
  - sphinxcontrib-napoleon
  - sphinx_rtd_theme >=1.2.1
  - pip
      - jcamp
